In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
df_sc = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()
df_sc

,composition,Tc,_Composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,19.0,56.0,37.0,30.360000,6.214400,26.0,3.0,...,2.110663,0.844265,1.013118,0.0,166.0,229.0,63.0,203.800000,30.240000,166.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,8.0,57.0,49.0,22.677795,16.074864,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,106.949534,102.911141,12.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,42.0,44.0,2.0,43.220000,0.951600,44.0,50.0,...,0.000000,0.000000,0.000000,0.0,194.0,229.0,35.0,207.650000,16.653000,194.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,50.0,76.0,26.0,58.000000,10.482759,50.0,37.0,...,0.000000,0.000000,0.000000,0.0,141.0,194.0,53.0,159.275862,23.947681,141.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,8.0,83.0,75.0,36.658000,27.869600,16.0,19.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,72.206000,49.328776,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Al4C3,0.00,Al4 C3,6.0,13.0,7.0,10.000000,3.428571,13.0,73.0,...,0.000000,0.000000,0.000000,0.0,194.0,225.0,31.0,211.714286,15.183673,225.0
16410,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,41.0,73.0,32.0,42.280000,2.457600,41.0,47.0,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,8.0,82.0,74.0,27.138250,19.616202,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,117.531250,105.531250,12.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,8.0,70.0,62.0,24.705426,17.870921,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,110.488372,105.359654,12.0
16413,La5Si3,1.60,La5 Si3,14.0,57.0,43.0,40.875000,20.156250,57.0,13.0,...,0.000000,0.000000,0.000000,0.0,194.0,227.0,33.0,206.375000,15.468750,194.0

In [3]:
df_sc["having_tc"] = (df_sc["Tc"] >= 10).astype(int)

In [4]:
X = df_sc.iloc[:, 3:-1]
y = df_sc['having_tc']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [6]:
X_train

,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,MagpieData mean MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
4445,8.0,57.0,49.0,24.915423,19.404046,8.0,13.0,87.0,74.0,62.692964,...,0.000000,0.000000,0.000000,0.000000,12.0,225.0,213.0,94.018479,94.085164,12.0
6319,8.0,57.0,49.0,23.206832,16.318042,8.0,7.0,87.0,80.0,63.668756,...,0.000000,0.000000,0.000000,0.000000,12.0,229.0,217.0,108.827013,102.622676,12.0
6320,41.0,46.0,5.0,42.200000,1.824000,41.0,47.0,62.0,15.0,50.600000,...,0.000000,0.000000,0.000000,0.000000,225.0,229.0,4.0,228.040000,1.459200,229.0
6080,16.0,62.0,46.0,30.698113,17.471342,16.0,23.0,88.0,65.0,66.160377,...,0.000000,0.000000,0.000000,0.000000,70.0,229.0,159.0,120.830189,60.420790,70.0
9360,26.0,52.0,26.0,32.104167,5.086806,26.0,4.0,90.0,86.0,60.718750,...,2.110663,0.879443,1.026017,2.110663,14.0,229.0,215.0,146.604167,96.690538,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13447,16.0,63.0,47.0,29.759271,14.323249,16.0,25.0,88.0,63.0,68.549122,...,0.000000,0.000000,0.000000,0.000000,70.0,229.0,159.0,145.554327,78.722333,70.0
5401,14.0,44.0,30.0,22.325000,4.162500,23.0,46.0,78.0,32.0,54.750000,...,0.000000,0.000000,0.000000,0.000000,194.0,229.0,35.0,225.875000,4.781250,229.0
862,5.0,76.0,71.0,28.666667,31.555556,5.0,57.0,72.0,15.0,67.000000,...,0.000000,0.000000,0.000000,0.000000,166.0,194.0,28.0,175.333333,12.444444,166.0
15833,8.0,60.0,52.0,22.578588,16.069517,8.0,7.0,87.0,80.0,64.600607,...,0.000000,0.000000,0.000000,0.000000,12.0,229.0,217.0,105.811693,102.145762,12.0
7286,5.0,40.0,35.0,8.266667,4.355556,5.0,44.0,72.0,28.0,69.866667,...,0.000000,0.000000,0.000000,0.000000,166.0,194.0,28.0,175.333333,12.444444,166.0

In [7]:
param_grid = {
    "n_estimators": [100, 200, 500],  # Number of trees in the forest
    "max_depth": [5, 10, 15],        # Maximum depth of individual trees
    "min_samples_split": [2, 5, 10],  # Minimum samples required to split a node
}

# param_grid = {
#     "n_estimators": [100, 200, 500, 1000],  # Increased range for number of trees
#     "max_depth": [5, 10],  # Lower range to potentially reduce overfitting
#     "min_samples_split": [2, 5, 10],
#     "min_samples_leaf": [1, 2, 5, 10],  # New parameter for leaf node samples
#     "max_features": ["auto", "sqrt", "log2"],  # New parameter for feature selection
#     "ccp_alpha": [0.0, 0.01, 0.1]  # New parameter for cost complexity pruning
# }

In [8]:
# Create the Random Forest classifier
model = RandomForestClassifier()

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring="accuracy", n_jobs=-1, verbose=2)

# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 500]},
             scoring='accuracy', verbose=2)

In [9]:
# Get the best model from the grid search
best_model = grid_search.best_estimator_

# Predict on the testing set
y_pred = best_model.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, y_pred)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9157303370786517
Confusion Matrix:
 [[2320  218]
 [ 127 1429]]
Precision: 0.8676381299332119
Recall: 0.9183804627249358
F1 Score: 0.8922884795504215
ROC-AUC Score: 0.9162430288407972

In [11]:
filename = 'sc_ep_rf_cl1.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [12]:
grid_search.best_params_

{'max_depth': 15, 'min_samples_split': 2, 'n_estimators': 500}

In [13]:
# Accuracy: 0.9149975574010747
# Confusion Matrix:
#  [[2314  224]
#  [ 124 1432]]
# Precision: 0.8647342995169082
# Recall: 0.9203084832904884
# F1 Score: 0.8916562889165629
# ROC-AUC Score: 0.9160250060266469

# 4320
# Accuracy: 0.8937469467513435
# Confusion Matrix:
#  [[2236  302]
#  [ 133 1423]]
# Precision: 0.8249275362318841
# Recall: 0.9145244215938303
# F1 Score: 0.867418469978665
# ROC-AUC Score: 0.8977665449182705