In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
df_sc = pd.read_csv("df_sc_ef_ElementFraction_ftd.csv").dropna()
df_sc

,composition,_Tc,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Al4C3,0.00,Al4 C3,0.0,0.0,0.0,0.0,0.0,0.428571,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16410,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16413,La5Si3,1.60,La5 Si3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df_sc["having_tc"] = (df_sc["_Tc"] >= 10).astype(int)

In [4]:
X = df_sc.iloc[:, 3:-1]
y = df_sc['having_tc']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [6]:
X_train

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
4445,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.573561,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6319,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.529928,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6320,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6080,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9360,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13447,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5401,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
862,0.0,0.0,0.0,0.0,0.666667,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15833,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.544419,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7286,0.0,0.0,0.0,0.0,0.666667,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# param_grid = {
#     "n_estimators": [100, 200, 500],  # Number of trees in the forest
#     "max_depth": [5, 10, 15],        # Maximum depth of individual trees
#     "min_samples_split": [2, 5, 10],  # Minimum samples required to split a node
# }

param_grid = {
    "n_estimators": [100, 200, 500],
    "max_depth": [5, 10, 15, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ['auto', 'sqrt', 'log2', 0.5, 0.7],
    "bootstrap": [True, False],
    "criterion": ["gini", "entropy"]
}

In [8]:
# Create the Random Forest classifier
model = RandomForestClassifier()

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring="accuracy", n_jobs=-1, verbose=2)

# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 2160 candidates, totalling 10800 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 15, None],
                         'max_features': ['auto', 'sqrt', 'log2', 0.5, 0.7],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 500]},
             scoring='accuracy', verbose=2)

In [9]:
# Get the best model from the grid search
best_model = grid_search.best_estimator_

# Predict on the testing set
y_pred = best_model.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, y_pred)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9196384953590621
Confusion Matrix:
 [[2354  184]
 [ 145 1411]]
Precision: 0.8846394984326019
Recall: 0.9068123393316195
F1 Score: 0.8955887019993654
ROC-AUC Score: 0.9171571546933907

In [11]:
filename = 'sc_ef_rf_cl.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [12]:
# Accuracy: 0.8683439179286762
# Confusion Matrix:
#  [[2226  312]
#  [ 227 1329]]
# Precision: 0.8098720292504571
# Recall: 0.8541131105398457
# F1 Score: 0.8314044416640601
# ROC-AUC Score: 0.8655908342297337

In [ ]:
#104000
# Accuracy: 0.9196384953590621
# Confusion Matrix:
#  [[2354  184]
#  [ 145 1411]]
# Precision: 0.8846394984326019
# Recall: 0.9068123393316195
# F1 Score: 0.8955887019993654
# ROC-AUC Score: 0.9171571546933907