In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, f1_score, precision_score, recall_score

In [2]:
df_sc = pd.read_csv("df_sc_ef_ElementFraction_ftd.csv").dropna()
df_sc

,composition,_Tc,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Al4C3,0.00,Al4 C3,0.0,0.0,0.0,0.0,0.0,0.428571,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16410,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16413,La5Si3,1.60,La5 Si3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df_sc = df_sc[df_sc["_Tc"]>=10]
df_sc

,composition,_Tc,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,La1.71Sr0.29Cu0.94Co0.06O4,33.00,La1.71 Sr0.29 Cu0.94 Co0.06 O4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Nb3Sn0.85Tl0.15,18.20,Nb3 Sn0.85 Tl0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Pb0.5Cu0.5Sr0.9La1.1Cu1O5.16,28.10,Pb0.5 Cu1.5 Sr0.9 La1.1 O5.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16400,Dy1Ba2Cu2.8Zn0.2O6.95,13.00,Dy1 Ba2 Cu2.8 Zn0.2 O6.95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16401,Bi2Ca2.5Sm0.5Cu2O8.33,22.00,Bi2 Ca2.5 Sm0.5 Cu2 O8.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16408,La1.78Sr0.22Cu0.9975Zn0.0025O4,19.25,La1.78 Sr0.22 Cu0.9975 Zn0.0025 O4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
X = df_sc.iloc[:, 3:]
y = df_sc['_Tc']

In [5]:
df_sc['_Tc']

0        31.20
1        40.10
6        33.00
10       18.20
11       28.10
         ...
16400    13.00
16401    22.00
16408    19.25
16411    63.60
16412    34.80
Name: _Tc, Length: 6248, dtype: float64

In [6]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
X_train.shape

(4686, 103)

In [8]:
# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [9]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

Fitting 5 folds for each of 81 candidates, totalling 405 fits

In [10]:
# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Adjusted R-squared:", r2_score(y_test, y_pred, multioutput='uniform_average'))

Mean Squared Error (MSE): 104.16987815449859
R-squared: 0.8788833654783211
Mean Absolute Error (MAE): 6.1709604490213135
Root Mean Squared Error (RMSE): 10.206364590514028
Adjusted R-squared: 0.8788833654783211

In [11]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,8.272757,0.355250,0.078126,2.614648e-02,None,1,2,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-105.345489,-119.161064,-120.002352,-110.473557,-134.703341,-117.937161,10.011227,4
1,15.528081,0.295044,0.174999,1.169310e-02,None,1,2,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-106.235793,-121.115283,-118.855705,-107.590343,-133.403672,-117.440159,9.928754,2
2,33.579776,0.383699,0.421976,1.420986e-01,None,1,2,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-106.697172,-117.074407,-115.854798,-109.195803,-133.377288,-116.439894,9.327569,1
3,7.275610,0.435727,0.087499,7.654227e-03,None,1,5,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-106.107469,-122.136584,-121.235175,-112.441239,-140.523150,-120.488724,11.629560,11
4,17.691632,1.069881,0.238358,3.292479e-02,None,1,5,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-105.826492,-121.463778,-117.639976,-110.823128,-135.077585,-118.166192,10.033294,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,14.453084,0.251362,0.171876,3.277466e-02,20,4,5,100,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-127.305760,-141.018216,-134.593674,-126.894919,-153.189018,-136.600317,9.790945,46
77,29.128348,0.305342,0.290624,7.654130e-03,20,4,5,200,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-127.567041,-142.549343,-134.963327,-123.547670,-151.416355,-136.008747,10.077773,40
78,7.168729,0.059620,0.125000,6.641573e-07,20,4,10,50,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-130.038395,-143.743625,-137.847090,-128.526392,-156.624573,-139.356015,10.235525,54
79,14.240585,0.164945,0.168749,4.122121e-02,20,4,10,100,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-125.565257,-143.293959,-135.223308,-126.927363,-153.218233,-136.845624,10.372018,47
80,27.065549,2.164253,0.262499,1.822223e-02,20,4,10,200,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-128.898502,-142.834330,-136.243086,-125.353566,-154.495083,-137.564913,10.395848,51

In [12]:
filename = 'sc_ef_best_model_rf__2.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [13]:
# # Example: Create a new data point (features) for prediction
# new_data_point = [[feature1_value, feature2_value, ...]]

# # Predict using the loaded model
# predicted_value = loaded_model.predict(new_data_point)

# print("Predicted value:", predicted_value)

In [14]:
# Mean Squared Error (MSE): 285.50798228513975
# R-squared: 0.5568746119199605
# Mean Absolute Error (MAE): 10.705040122111116
# Root Mean Squared Error (RMSE): 16.896981454838013
# Adjusted R-squared: 0.5568746119199605


# On 9000 rows
# Mean Squared Error (MSE): 138.87230308323188
# R-squared: 0.8021012250455234
# Mean Absolute Error (MAE): 6.131617541973627
# Root Mean Squared Error (RMSE): 11.784409322627583
# Adjusted R-squared: 0.8021012250455234

# Mean Squared Error (MSE): 127.29734257361541
# R-squared: 0.827537081963444
# Mean Absolute Error (MAE): 5.243760973322503
# Root Mean Squared Error (RMSE): 11.282612400220767
# Adjusted R-squared: 0.827537081963444

# EF_filtered
# Mean Squared Error (MSE): 104.16987815449859
# R-squared: 0.8788833654783211
# Mean Absolute Error (MAE): 6.1709604490213135
# Root Mean Squared Error (RMSE): 10.206364590514028
# Adjusted R-squared: 0.8788833654783211

# Superconductivity
df_sc_ep = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()

df_sc_ep = df_sc_ep.iloc[0:700]

X = df_sc_ep.iloc[:, 3:]
y = df_sc_ep['Tc']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

# Define a function to create the target column
def is_semiconductor(Tc):
    # A semiconductor has a band gap between 0.1 and 4 eV
    return 0.1 <= Tc <= 4