In [1]:
import matminer
import pandas as pd
from matminer import featurizers
from matminer.datasets import load_dataset
from pymatgen.core.composition import Composition
from sklearn.preprocessing import StandardScaler
from matminer.featurizers.composition import ElementProperty, ElementFraction

In [2]:
# Superconductivity
df_sc = load_dataset("superconductivity2018")

df_sc

                            composition     Tc
0                       Ba0.4K0.6Fe2As2  31.20
1             Ca0.4Ba1.25La1.25Cu3O6.98  40.10
2                          Mo0.39Ru0.61   6.90
3                            Tm4Os6Sn19   1.10
4             Nd1Bi0.99Pb0.01S2F0.3O0.7   4.85
...                                 ...    ...
16409                             Al4C3   0.00
16410                      Nb0.96Ta0.04   8.87
16411  Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8  63.60
16412              Yb0.5Pr0.5Ba2Cu3O6.9  34.80
16413                            La5Si3   1.60

[16414 rows x 2 columns]

In [3]:
composition = Composition("Ba0.4K0.6Fe2As2")
print(composition)
ef_featurizer = ElementFraction()
ef_features = ef_featurizer.featurize(composition)

print(ef_features)

Ba0.4 K0.6 Fe2 As2

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.12,
 0,
 0,
 0,
 0,
 0,
 0,
 0.4,
 0,
 0,
 0,
 0,
 0,
 0,
 0.4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.08,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [4]:
# Split the dataframe into features and target
def create_composition(formula):
    try:
        return Composition(formula)
    except ValueError:
        print(f"Error parsing formula: {formula}")

df_sc["_Composition"] = df_sc['composition'].apply(create_composition).to_frame()

df_sc

Error parsing formula: Eu1.45Pr0.05Ce0.5Sr2Cu2Nb1O10=z
Error parsing formula: Sm1Ba-1Cu3O6.94
Error parsing formula: Y2C2Br0.5!1.5
Error parsing formula: Hg0.3Pb0.7Sr1.75La0.25Cu1O4+2
Error parsing formula: Hg1Sr2Ho0.333Ce0.667Cu2O6=z
Error parsing formula: B1Sr2Ca3Cu4O2N+3
Error parsing formula: B1Sr2Ca4Cu5O2N+3
Error parsing formula: B1Sr2Ca2Cu3O2N+3

                            composition     Tc                 _Composition
0                       Ba0.4K0.6Fe2As2  31.20              (Ba, K, Fe, As)
1             Ca0.4Ba1.25La1.25Cu3O6.98  40.10          (Ca, Ba, La, Cu, O)
2                          Mo0.39Ru0.61   6.90                     (Mo, Ru)
3                            Tm4Os6Sn19   1.10                 (Tm, Os, Sn)
4             Nd1Bi0.99Pb0.01S2F0.3O0.7   4.85        (Nd, Bi, Pb, S, F, O)
...                                 ...    ...                          ...
16409                             Al4C3   0.00                      (Al, C)
16410                      Nb0.96Ta0.04   8.87                     (Nb, Ta)
16411  Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8  63.60  (Pb, Sr, Ho, Ca, Cu, Al, O)
16412              Yb0.5Pr0.5Ba2Cu3O6.9  34.80          (Yb, Pr, Ba, Cu, O)
16413                            La5Si3   1.60                     (La, Si)

[16414 rows x 3 columns]

In [5]:
# Use ElementFraction instead of ElementProperty
featurizer = ElementFraction()
df_sc = df_sc.rename(columns={"Tc": "_Tc"})  # Rename to avoid conflict
df_sc_ftd = featurizer.featurize_dataframe(df_sc, col_id='_Composition', ignore_errors=True)

ElementFraction:   0%|          | 0/16414 [00:00<?, ?it/s]

NameError: name 'df_sc_ftd_ef' is not defined

In [6]:
df_sc_ftd

,composition,_Tc,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,"(Ba, K, Fe, As)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,"(Ca, Ba, La, Cu, O)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Mo0.39Ru0.61,6.90,"(Mo, Ru)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Tm4Os6Sn19,1.10,"(Tm, Os, Sn)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,"(Nd, Bi, Pb, S, F, O)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Al4C3,0.00,"(Al, C)",0.0,0.0,0.0,0.0,0.0,0.428571,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16410,Nb0.96Ta0.04,8.87,"(Nb, Ta)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,"(Pb, Sr, Ho, Ca, Cu, Al, O)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,"(Yb, Pr, Ba, Cu, O)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16413,La5Si3,1.60,"(La, Si)",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df_sc_ftd.to_csv("df_sc_ef_ElementFraction_ftd.csv", index = False)