In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, f1_score, precision_score, recall_score

In [2]:
df_sc = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()
df_sc

,composition,Critical Temp,_Composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,19.0,56.0,37.0,30.360000,6.214400,26.0,3.0,...,2.110663,0.844265,1.013118,0.0,166.0,229.0,63.0,203.800000,30.240000,166.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,8.0,57.0,49.0,22.677795,16.074864,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,106.949534,102.911141,12.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,42.0,44.0,2.0,43.220000,0.951600,44.0,50.0,...,0.000000,0.000000,0.000000,0.0,194.0,229.0,35.0,207.650000,16.653000,194.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,50.0,76.0,26.0,58.000000,10.482759,50.0,37.0,...,0.000000,0.000000,0.000000,0.0,141.0,194.0,53.0,159.275862,23.947681,141.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,8.0,83.0,75.0,36.658000,27.869600,16.0,19.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,72.206000,49.328776,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16401,Al4C3,0.00,Al4 C3,6.0,13.0,7.0,10.000000,3.428571,13.0,73.0,...,0.000000,0.000000,0.000000,0.0,194.0,225.0,31.0,211.714286,15.183673,225.0
16402,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,41.0,73.0,32.0,42.280000,2.457600,41.0,47.0,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
16403,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,8.0,82.0,74.0,27.138250,19.616202,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,117.531250,105.531250,12.0
16404,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,8.0,70.0,62.0,24.705426,17.870921,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,110.488372,105.359654,12.0
16405,La5Si3,1.60,La5 Si3,14.0,57.0,43.0,40.875000,20.156250,57.0,13.0,...,0.000000,0.000000,0.000000,0.0,194.0,227.0,33.0,206.375000,15.468750,194.0

In [3]:
df_sc = df_sc[df_sc["Critical Temp"]>=10]
df_sc

,composition,Critical Temp,_Composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,19.0,56.0,37.0,30.360000,6.214400,26.0,3.0,...,2.110663,0.844265,1.013118,0.0,166.0,229.0,63.0,203.800000,30.240000,166.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,8.0,57.0,49.0,22.677795,16.074864,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,106.949534,102.911141,12.0
6,La1.71Sr0.29Cu0.94Co0.06O4,33.00,La1.71 Sr0.29 Cu0.94 Co0.06 O4,8.0,57.0,49.0,24.195714,18.509388,8.0,8.0,...,1.548471,0.013273,0.026318,0.0,12.0,225.0,213.0,95.447143,95.368163,12.0
10,Nb3Sn0.85Tl0.15,18.20,Nb3 Sn0.85 Tl0.15,41.0,81.0,40.0,44.412500,5.118750,41.0,47.0,...,0.000000,0.000000,0.000000,0.0,141.0,229.0,88.0,208.987500,30.018750,229.0
11,Pb0.5Cu0.5Sr0.9La1.1Cu1O5.16,28.10,Pb0.5 Cu1.5 Sr0.9 La1.1 O5.16,8.0,82.0,74.0,24.310044,18.375508,8.0,8.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,101.290393,100.597910,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16392,Dy1Ba2Cu2.8Zn0.2O6.95,13.00,Dy1 Ba2 Cu2.8 Zn0.2 O6.95,8.0,66.0,58.0,24.772201,18.002594,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,108.432432,103.506626,12.0
16393,Bi2Ca2.5Sm0.5Cu2O8.33,22.00,Bi2 Ca2.5 Sm0.5 Cu2 O8.33,8.0,83.0,75.0,24.242661,19.035620,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,79.547293,91.032425,12.0
16400,La1.78Sr0.22Cu0.9975Zn0.0025O4,19.25,La1.78 Sr0.22 Cu0.9975 Zn0.0025 O4,8.0,57.0,49.0,24.403214,18.746531,8.0,8.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,95.391786,95.304898,12.0
16403,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,8.0,82.0,74.0,27.138250,19.616202,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,117.531250,105.531250,12.0
16404,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,8.0,70.0,62.0,24.705426,17.870921,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,110.488372,105.359654,12.0

In [4]:
X = df_sc.iloc[:, 3:]
y = df_sc['Critical Temp']

In [5]:
df_sc['Critical Temp']

0        31.20
1        40.10
6        33.00
10       18.20
11       28.10
         ...
16392    13.00
16393    22.00
16400    19.25
16403    63.60
16404    34.80
Name: Critical Temp, Length: 6252, dtype: float64

In [6]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
X_train.shape

(4689, 132)

In [8]:
# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 3, 5],
    'min_samples_leaf': [1, 2]
}

In [9]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Evaluate the model
print(grid_search.best_estimator_)
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

Fitting 5 folds for each of 54 candidates, totalling 270 fits
RandomForestRegressor(max_depth=20)

In [10]:
# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Adjusted R-squared:", r2_score(y_test, y_pred, multioutput='uniform_average'))

Mean Squared Error (MSE): 115.7421258933955
R-squared: 0.8691342850662724
Mean Absolute Error (MAE): 6.676580358889026
Root Mean Squared Error (RMSE): 10.758351448683738
Adjusted R-squared: 0.8691342850662724

In [11]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,27.115740,0.546863,0.057997,2.226864e-02,NaN,1,2,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-119.889448,-120.779395,-126.247350,-119.813497,-113.930932,-120.132124,3.909735,9
1,54.022771,0.482020,0.083303,5.603474e-03,NaN,1,2,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-119.966609,-120.731606,-127.844523,-119.797867,-112.661647,-120.200451,4.811742,10
2,106.825036,1.045727,0.168195,2.077267e-02,NaN,1,2,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-117.526200,-121.332901,-126.118450,-117.567048,-113.109270,-119.130774,4.357875,4
3,25.009320,0.561876,0.035322,4.518739e-03,NaN,1,3,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-119.864171,-124.952171,-127.860476,-121.430875,-115.104775,-121.842494,4.367293,26
4,50.083958,0.262235,0.072719,3.898232e-03,NaN,1,3,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-117.569531,-123.439826,-126.696604,-119.030852,-113.235727,-119.994508,4.675009,8
5,99.452260,1.197610,0.142052,4.121781e-03,NaN,1,3,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-117.937360,-121.867284,-126.520757,-118.136656,-112.477774,-119.387966,4.657135,5
6,23.297258,0.373198,0.035999,4.899014e-03,NaN,1,5,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-123.418468,-124.699788,-126.796590,-119.604802,-113.480298,-121.599989,4.686799,22
7,46.316936,0.207727,0.071273,6.821047e-03,NaN,1,5,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-121.050116,-123.029609,-124.624254,-120.258552,-115.129958,-120.818498,3.227986,14
8,92.256335,1.043546,0.131786,7.288932e-03,NaN,1,5,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-121.340318,-121.385975,-127.127556,-120.399750,-111.689360,-120.388592,4.959656,11
9,21.987598,0.232224,0.038638,4.493995e-03,NaN,2,2,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-123.331201,-125.796088,-131.396948,-125.715202,-114.541902,-124.156268,5.489326,35
10,44.111446,0.437275,0.066034,8.066931e-03,NaN,2,2,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-119.910504,-122.782930,-128.033936,-121.117216,-115.622459,-121.493409,4.038725,21
11,88.144803,0.177056,0.130695,1.405622e-03,NaN,2,2,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-119.191326,-123.238637,-129.573393,-121.372198,-113.482593,-121.371630,5.248719,18
12,22.118418,0.252945,0.035996,4.901098e-03,NaN,2,3,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-120.665941,-129.710283,-133.555944,-119.892047,-116.221696,-124.009182,6.517917,34
13,44.328098,0.236085,0.071380,2.613992e-03,NaN,2,3,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-117.628051,-124.895590,-129.330708,-120.787384,-113.542424,-121.236831,5.501392,16
14,89.103568,0.921814,0.127403,3.926740e-03,NaN,2,3,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-119.962630,-124.900082,-129.276862,-121.189425,-113.262548,-121.718309,5.331368,25
15,21.564496,0.161295,0.037998,4.000616e-03,NaN,2,5,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-121.648152,-125.114466,-132.717088,-121.778036,-118.357964,-123.923141,4.888783,33
16,43.386895,0.554046,0.061996,3.999424e-03,NaN,2,5,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-121.158765,-126.528466,-130.821114,-119.832991,-113.957880,-122.459843,5.785172,28
17,86.579059,0.718924,0.137386,2.161241e-02,NaN,2,5,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-118.638158,-121.419618,-129.198634,-121.614184,-116.032063,-121.380531,4.411476,19
18,15.587634,0.090107,0.029998,1.689915e-06,10.0,1,2,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-144.434246,-154.802980,-152.278761,-149.263187,-146.865201,-149.528875,3.701325,41
19,31.527192,0.421266,0.051997,4.000139e-03,10.0,1,2,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-146.674649,-147.979299,-157.500742,-155.292292,-142.614456,-150.012287,5.548985,43
20,62.469584,0.115551,0.095992,4.896875e-03,10.0,1,2,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-145.096557,-150.708896,-157.393578,-147.574343,-142.678578,-148.690390,5.101430,37
21,15.642253,0.312264,0.028138,7.706310e-03,10.0,1,3,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-144.644622,-152.685515,-156.984335,-145.385448,-147.073652,-149.354714,4.742334,38
22,30.809681,0.221154,0.053998,7.999539e-03,10.0,1,3,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-145.018363,-148.912666,-157.400726,-154.192887,-147.299761,-150.564881,4.561708,46
23,61.871423,0.410833,0.091994,3.999782e-03,10.0,1,3,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-146.897795,-151.936447,-158.470002,-150.099578,-144.569477,-150.394660,4.771502,45
24,15.232187,0.084223,0.027999,3.999639e-03,10.0,1,5,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-151.721833,-153.398630,-159.692510,-147.143978,-143.008971,-150.993184,5.666735,49
25,30.402961,0.194509,0.049997,8.714517e-07,10.0,1,5,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-145.720544,-150.979403,-157.225227,-148.644561,-144.519293,-149.417806,4.509046,39
26,61.020553,0.539909,0.099568,1.251608e-02,10.0,1,5,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-144.947149,-154.490692,-159.783433,-148.799959,-143.796615,-150.363569,6.011229,44
27,15.307163,0.099857,0.031998,3.998828e-03,10.0,2,2,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-150.273085,-150.761268,-162.834754,-152.068230,-144.462908,-152.080049,5.978109,53
28,30.157658,0.098490,0.049996,5.091228e-07,10.0,2,2,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-142.362427,-154.640145,-166.201498,-150.458956,-143.276928,-151.387991,8.696318,51
29,60.748549,0.293228,0.097994,7.482046e-03,10.0,2,2,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-145.792671,-152.279306,-157.598901,-150.690647,-143.030669,-149.878439,5.091460,42
30,15.032807,0.062268,0.029315,5.561633e-03,10.0,2,3,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-149.281402,-153.371861,-160.573555,-155.097916,-145.723549,-152.809657,5.069356,54
31,29.917237,0.161772,0.049997,1.181556e-06,10.0,2,3,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-145.868546,-155.415264,-162.728861,-149.321515,-142.557728,-151.178383,7.173879,50
32,59.983758,0.285123,0.093993,4.899248e-03,10.0,2,3,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-145.049201,-152.062726,-160.223357,-148.174405,-142.107789,-149.523495,6.289146,40
33,14.961431,0.123675,0.027999,7.483206e-03,10.0,2,5,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-147.341617,-150.741580,-163.794201,-151.490280,-144.092423,-151.492020,6.691587,52
34,29.880810,0.177838,0.049998,1.373755e-06,10.0,2,5,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-147.001499,-151.390042,-163.048457,-149.325479,-142.739107,-150.700917,6.810354,48
35,59.553659,0.257315,0.093993,4.898099e-03,10.0,2,5,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-146.891742,-152.535241,-160.485163,-151.027552,-142.113539,-150.610647,6.122337,47
36,24.988326,0.222216,0.044476,5.537681e-03,20.0,1,2,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-120.324942,-122.085475,-126.725511,-117.588115,-112.015026,-119.747814,4.877424,6
37,49.864674,0.413228,0.069996,3.162980e-07,20.0,1,2,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-117.588597,-120.219087,-123.276081,-120.724504,-112.693729,-118.900400,3.590445,1
38,99.846084,0.419373,0.139992,7.136645e-07,20.0,1,2,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-118.730469,-120.566490,-124.665795,-118.539180,-112.741344,-119.048656,3.847052,3
39,23.834793,0.211983,0.037998,4.000211e-03,20.0,1,3,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-119.648121,-121.448081,-125.600832,-121.095345,-115.299601,-120.618396,3.315767,13
40,47.446128,0.462551,0.069823,5.366574e-03,20.0,1,3,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-118.586067,-121.854156,-124.908927,-118.782904,-110.617547,-118.949920,4.765146,2
41,94.772253,0.766262,0.132058,4.129672e-03,20.0,1,3,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-117.025906,-123.006824,-128.149403,-118.696343,-112.587975,-119.893290,5.308101,7
42,22.260448,0.307947,0.033999,4.898508e-03,20.0,1,5,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-122.651127,-126.502636,-128.938684,-122.784882,-117.134542,-123.602374,4.007337,32
43,44.268104,0.278293,0.065995,4.898508e-03,20.0,1,5,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-120.985452,-124.035406,-125.826753,-122.152384,-112.534878,-121.106975,4.592178,15
44,88.901673,0.908661,0.125957,4.869984e-03,20.0,1,5,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-118.990645,-122.867155,-125.161556,-121.111684,-113.841193,-120.394447,3.854085,12
45,21.483604,0.289155,0.035998,4.898352e-03,20.0,2,2,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-118.869259,-125.358315,-131.796395,-122.313939,-118.413359,-123.350254,4.917231,31
46,43.103815,0.362405,0.061354,2.715373e-03,20.0,2,2,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-120.407572,-121.273511,-128.373564,-121.984871,-114.200246,-121.247953,4.509866,17
47,85.829016,0.525372,0.121991,9.797862e-03,20.0,2,2,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-121.112021,-124.217578,-125.965813,-122.057048,-114.074653,-121.485422,4.072451,20
48,21.657597,0.185652,0.033998,4.898430e-03,20.0,2,3,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-122.561217,-124.303588,-129.945314,-123.064645,-116.615554,-123.298064,4.253243,30
49,43.255852,0.356056,0.063996,4.898488e-03,20.0,2,3,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-118.341547,-122.926139,-129.198831,-123.082030,-116.738243,-122.057358,4.356733,27
50,86.639103,1.096220,0.123237,5.400566e-03,20.0,2,3,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-120.723775,-123.263281,-126.955409,-122.872728,-114.307480,-121.624535,4.171627,23
51,21.508922,0.361997,0.041998,1.938926e-02,20.0,2,5,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-122.248496,-125.856871,-131.184593,-126.468077,-120.211856,-125.193979,3.780149,36
52,42.576952,0.438399,0.064792,4.489785e-03,20.0,2,5,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-122.434764,-125.165104,-131.665274,-122.717262,-113.638632,-123.124207,5.791928,29
53,79.393452,7.513887,0.106716,1.951680e-02,20.0,2,5,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-118.568561,-124.164315,-129.078158,-123.629919,-112.940580,-121.676307,5.491178,24

In [12]:
# Assuming you have the 'best_model' already trained
filename = 'sc_ep_best_model_yet.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [13]:
# Mean Squared Error (MSE): 128.98800337163584
# R-squared: 0.8252465683616537
# Mean Absolute Error (MAE): 5.709746142892196
# Root Mean Squared Error (RMSE): 11.357288557205713
# Adjusted R-squared: 0.8252465683616537

In [14]:
# # Example: Create a new data point (features) for prediction
# new_data_point = [[feature1_value, feature2_value, ...]]

# # Predict using the loaded model
# predicted_value = loaded_model.predict(new_data_point)

# print("Predicted value:", predicted_value)

In [15]:
# Mean Squared Error (MSE): 3.6857372748369126e-06
# R-squared: 0.9973982295162389
# Mean Absolute Error (MAE): 6.51226710603105e-05
# Root Mean Squared Error (RMSE): 0.0019198274075647823
# Adjusted R-squared: 0.9973982295162389

# Superconductivity
df_sc_ep = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()

df_sc_ep = df_sc_ep.iloc[0:700]

X = df_sc_ep.iloc[:, 3:]
y = df_sc_ep['Tc']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

# Define a function to create the target column
def is_semiconductor(Tc):
    # A semiconductor has a band gap between 0.1 and 4 eV
    return 0.1 <= Tc <= 4