In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, f1_score, precision_score, recall_score

In [2]:
df_sc = pd.read_csv("df_sc_ef_ElementFraction_ftd.csv").dropna()
df_sc

,composition,Critical Temp,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16401,Al4C3,0.00,Al4 C3,0.0,0.0,0.0,0.0,0.0,0.428571,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16402,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16403,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16404,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16405,La5Si3,1.60,La5 Si3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df_sc = df_sc[df_sc["Critical Temp"]>=10]
df_sc

,composition,Critical Temp,_Composition,H,He,Li,Be,B,C,N,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,La1.71Sr0.29Cu0.94Co0.06O4,33.00,La1.71 Sr0.29 Cu0.94 Co0.06 O4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Nb3Sn0.85Tl0.15,18.20,Nb3 Sn0.85 Tl0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Pb0.5Cu0.5Sr0.9La1.1Cu1O5.16,28.10,Pb0.5 Cu1.5 Sr0.9 La1.1 O5.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16392,Dy1Ba2Cu2.8Zn0.2O6.95,13.00,Dy1 Ba2 Cu2.8 Zn0.2 O6.95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16393,Bi2Ca2.5Sm0.5Cu2O8.33,22.00,Bi2 Ca2.5 Sm0.5 Cu2 O8.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16400,La1.78Sr0.22Cu0.9975Zn0.0025O4,19.25,La1.78 Sr0.22 Cu0.9975 Zn0.0025 O4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16403,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16404,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
X = df_sc.iloc[:, 3:]
y = df_sc['Critical Temp']

In [5]:
df_sc['Critical Temp']

0        31.20
1        40.10
6        33.00
10       18.20
11       28.10
         ...
16392    13.00
16393    22.00
16400    19.25
16403    63.60
16404    34.80
Name: Critical Temp, Length: 6252, dtype: float64

In [6]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
X_train.shape

(4689, 103)

In [8]:
# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 3, 5],
    'min_samples_leaf': [1, 2]
}

In [9]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Evaluate the model
print(grid_search.best_estimator_)
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

Fitting 5 folds for each of 54 candidates, totalling 270 fits
RandomForestRegressor()

In [10]:
# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Adjusted R-squared:", r2_score(y_test, y_pred, multioutput='uniform_average'))

Mean Squared Error (MSE): 117.31768325987186
R-squared: 0.867352855534099
Mean Absolute Error (MAE): 6.414489465063787
Root Mean Squared Error (RMSE): 10.831328785512508
Adjusted R-squared: 0.867352855534099

In [11]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,5.349472,0.292747,0.058785,0.008132,NaN,1,2,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-126.178132,-103.035693,-120.861936,-106.392936,-130.358619,-117.365463,10.811561,7
1,9.778042,0.094785,0.095970,0.005862,NaN,1,2,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-120.971747,-103.544532,-116.319098,-104.171392,-128.589163,-114.719186,9.697003,1
2,19.865186,0.190601,0.182541,0.012496,NaN,1,2,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-121.113435,-105.688192,-117.080340,-103.759892,-130.050153,-115.538402,9.796014,2
3,4.531934,0.076460,0.045787,0.004307,NaN,1,3,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-122.903202,-108.525529,-116.831937,-104.379161,-133.182254,-117.164416,10.273349,5
4,9.069070,0.086333,0.092172,0.022430,NaN,1,3,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-122.765649,-105.291612,-117.224959,-105.367043,-129.205757,-115.971004,9.480419,4
5,18.453441,0.456507,0.166947,0.006839,NaN,1,3,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-120.812479,-104.013793,-117.997906,-105.472319,-130.090716,-115.677443,9.794701,3
6,4.824240,0.318951,0.042387,0.002154,NaN,1,5,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-125.393612,-111.638909,-116.236656,-105.005703,-133.435241,-118.342024,10.047406,13
7,8.502454,0.103081,0.079776,0.005739,NaN,1,5,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-123.628010,-107.084348,-119.079675,-107.132274,-132.706441,-117.926150,9.862568,11
8,17.120472,0.187120,0.148753,0.009258,NaN,1,5,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-123.451308,-108.376885,-118.052654,-107.538256,-129.680739,-117.419968,8.561886,8
9,3.886344,0.032880,0.040987,0.001790,NaN,2,2,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-131.888557,-115.248218,-119.985415,-113.452271,-135.281892,-123.171271,8.832232,31
10,7.722506,0.050607,0.075576,0.005313,NaN,2,2,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-127.827896,-112.826389,-119.446316,-107.319196,-134.753365,-120.434632,9.905183,19
11,15.375235,0.161755,0.135756,0.002226,NaN,2,2,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-128.944943,-113.400134,-122.201825,-107.132037,-133.819836,-121.099755,9.787168,20
12,3.835760,0.033760,0.039189,0.000980,NaN,2,3,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-132.798129,-113.759986,-122.028342,-108.852679,-134.070150,-122.301857,10.025799,25
13,7.714107,0.081773,0.072776,0.003654,NaN,2,3,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-132.485996,-113.742612,-122.966987,-106.197930,-133.735046,-121.825714,10.642748,22
14,15.427019,0.141223,0.140954,0.003160,NaN,2,3,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-129.088774,-115.765642,-121.918486,-107.744768,-132.833917,-121.470317,9.036672,21
15,3.775779,0.057640,0.039389,0.001355,NaN,2,5,50,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-129.992082,-118.357659,-121.193803,-107.798474,-135.830703,-122.634544,9.682442,27
16,7.537764,0.093720,0.072977,0.007820,NaN,2,5,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-131.164369,-114.130342,-122.661284,-109.641788,-134.109831,-122.341523,9.435515,26
17,15.029942,0.160924,0.136957,0.003464,NaN,2,5,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",-130.208872,-114.936720,-121.842866,-108.152641,-134.196494,-121.867519,9.567824,23
18,2.514788,0.034240,0.032389,0.006436,10.0,1,2,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-155.273930,-149.575600,-154.043029,-139.191903,-159.457857,-151.508464,6.917069,42
19,5.036572,0.065341,0.051185,0.002228,10.0,1,2,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-156.320831,-148.228503,-152.066271,-135.379304,-159.528454,-150.304672,8.383945,37
20,10.008367,0.081070,0.095970,0.004775,10.0,1,2,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-159.688632,-147.982956,-151.290727,-136.342017,-160.441923,-151.149251,8.815604,40
21,2.478798,0.015546,0.028992,0.002190,10.0,1,3,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-163.565081,-149.120678,-152.759361,-138.294231,-157.545166,-152.256903,8.495707,49
22,4.933006,0.022888,0.052384,0.001958,10.0,1,3,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-158.650245,-146.881541,-151.337149,-137.581153,-157.905130,-150.471044,7.771087,39
23,9.891003,0.101115,0.099769,0.006044,10.0,1,3,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-157.743183,-148.657943,-149.634993,-136.112385,-159.624780,-150.354657,8.327840,38
24,2.431413,0.021870,0.030192,0.003917,10.0,1,5,50,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-154.111773,-148.577976,-156.006574,-139.537578,-162.071081,-152.060996,7.601875,48
25,4.872626,0.034781,0.052784,0.002636,10.0,1,5,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-160.621020,-148.828803,-152.854418,-138.122986,-159.757281,-152.036901,8.220080,47
26,9.860613,0.123630,0.095171,0.003708,10.0,1,5,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",-157.619309,-148.422593,-151.483624,-137.791583,-160.710134,-151.205448,7.990371,41
27,2.404022,0.030212,0.031392,0.004962,10.0,2,2,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-160.025008,-150.326950,-153.321783,-137.116824,-161.238363,-152.405785,8.660022,50
28,4.849833,0.051455,0.052184,0.002924,10.0,2,2,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-161.017159,-150.322054,-155.141610,-136.415781,-160.658459,-152.711013,9.047690,52
29,9.635688,0.087102,0.094170,0.003368,10.0,2,2,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-160.423716,-147.783428,-153.036619,-135.976701,-160.487138,-151.541520,9.138267,43
30,2.431015,0.023820,0.028592,0.001020,10.0,2,3,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-164.652163,-151.214110,-156.318317,-137.676846,-160.734666,-154.119221,9.363059,54
31,4.853432,0.085973,0.052583,0.001624,10.0,2,3,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-159.996088,-147.403947,-152.936524,-137.528985,-161.035452,-151.780199,8.680395,45
32,9.682673,0.151237,0.093769,0.003059,10.0,2,3,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-161.119815,-148.312136,-153.619207,-135.150585,-161.734485,-151.987245,9.778091,46
33,2.388427,0.021436,0.029592,0.002244,10.0,2,5,50,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-157.160733,-150.117599,-156.285782,-139.339995,-163.670187,-153.314859,8.202064,53
34,4.784654,0.028037,0.051983,0.003686,10.0,2,5,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-164.321667,-149.581047,-153.990853,-133.431123,-162.203857,-152.705709,11.027875,51
35,9.747453,0.305349,0.102767,0.013682,10.0,2,5,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",-161.394669,-148.508722,-153.128872,-134.831614,-159.948191,-151.562414,9.578027,44
36,4.586117,0.255161,0.053584,0.021734,20.0,1,2,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-121.060302,-108.261262,-120.729621,-108.332434,-129.740806,-117.624885,8.273622,9
37,8.558635,0.226968,0.076977,0.003161,20.0,1,2,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-122.916132,-105.915696,-120.438114,-105.844285,-133.058261,-117.634498,10.487972,10
38,16.525062,0.077303,0.143754,0.006880,20.0,1,2,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-121.661375,-107.348331,-121.174006,-106.828928,-129.314306,-117.265389,8.798251,6
39,3.933330,0.039705,0.039388,0.001356,20.0,1,3,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-124.352957,-110.511363,-121.485705,-105.879743,-129.603079,-118.366569,8.825532,14
40,7.865260,0.034608,0.069978,0.000895,20.0,1,3,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-124.932605,-108.506447,-120.638951,-107.641616,-128.482433,-118.040410,8.512602,12
41,15.702529,0.090702,0.138956,0.011709,20.0,1,3,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-125.844275,-107.976532,-120.140020,-108.110948,-130.914919,-118.597339,9.267003,15
42,3.749789,0.040300,0.039388,0.002870,20.0,1,5,50,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-127.862355,-112.957607,-120.910700,-106.205818,-131.545512,-119.896398,9.335587,18
43,7.490781,0.082822,0.067978,0.002282,20.0,1,5,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-126.799502,-109.652127,-122.075812,-107.721404,-132.334242,-119.716617,9.592879,17
44,14.933775,0.139050,0.129560,0.003381,20.0,1,5,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",-124.678339,-109.970854,-121.259477,-108.151488,-131.290929,-119.070217,8.804621,16
45,3.595038,0.049264,0.036390,0.001356,20.0,2,2,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-128.091197,-115.718579,-126.068768,-112.548584,-135.459083,-123.577242,8.380352,33
46,7.164885,0.062172,0.072977,0.005328,20.0,2,2,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-132.479281,-116.720867,-123.045176,-110.030900,-135.155089,-123.486263,9.423882,32
47,14.300581,0.097619,0.126359,0.001356,20.0,2,2,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-131.428270,-114.363592,-123.605844,-107.773412,-134.206264,-122.275476,10.007947,24
48,3.588440,0.026946,0.039989,0.003577,20.0,2,3,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-133.553524,-116.541706,-123.387899,-110.177496,-134.502627,-123.632650,9.465334,34
49,7.249457,0.057077,0.069179,0.002560,20.0,2,3,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-130.590136,-116.159574,-123.395787,-108.186556,-136.180083,-122.902427,9.976606,28
50,14.379556,0.151666,0.130558,0.004839,20.0,2,3,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-131.182874,-115.397287,-122.780847,-109.532836,-136.468076,-123.072384,9.874574,30
51,3.551850,0.054007,0.037989,0.002280,20.0,2,5,50,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-128.740746,-115.275195,-127.678849,-107.634317,-139.724240,-123.810670,11.198561,35
52,6.987541,0.083882,0.069379,0.004363,20.0,2,5,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-130.740732,-116.444385,-126.441979,-109.479252,-136.645147,-123.950299,9.790072,36
53,13.462654,1.265937,0.122557,0.025128,20.0,2,5,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",-130.412349,-117.084937,-123.537086,-107.801772,-136.070981,-122.981425,9.920225,29

In [12]:
filename = 'sc_ef_best_model_yet.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [13]:
# # Example: Create a new data point (features) for prediction
# new_data_point = [[feature1_value, feature2_value, ...]]

# # Predict using the loaded model
# predicted_value = loaded_model.predict(new_data_point)

# print("Predicted value:", predicted_value)

In [14]:
# Mean Squared Error (MSE): 285.50798228513975
# R-squared: 0.5568746119199605
# Mean Absolute Error (MAE): 10.705040122111116
# Root Mean Squared Error (RMSE): 16.896981454838013
# Adjusted R-squared: 0.5568746119199605


# On 9000 rows
# Mean Squared Error (MSE): 138.87230308323188
# R-squared: 0.8021012250455234
# Mean Absolute Error (MAE): 6.131617541973627
# Root Mean Squared Error (RMSE): 11.784409322627583
# Adjusted R-squared: 0.8021012250455234

# Mean Squared Error (MSE): 127.29734257361541
# R-squared: 0.827537081963444
# Mean Absolute Error (MAE): 5.243760973322503
# Root Mean Squared Error (RMSE): 11.282612400220767
# Adjusted R-squared: 0.827537081963444

# EF_filtered
# Mean Squared Error (MSE): 104.16987815449859
# R-squared: 0.8788833654783211
# Mean Absolute Error (MAE): 6.1709604490213135
# Root Mean Squared Error (RMSE): 10.206364590514028
# Adjusted R-squared: 0.8788833654783211

# Superconductivity
df_sc_ep = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()

df_sc_ep = df_sc_ep.iloc[0:700]

X = df_sc_ep.iloc[:, 3:]
y = df_sc_ep['Tc']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

# Define a function to create the target column
def is_semiconductor(Tc):
    # A semiconductor has a band gap between 0.1 and 4 eV
    return 0.1 <= Tc <= 4