In [1]:
import matminer
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, f1_score, precision_score, recall_score

In [2]:
df_sc = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()
df_sc

,composition,Tc,_Composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,19.0,56.0,37.0,30.360000,6.214400,26.0,3.0,...,2.110663,0.844265,1.013118,0.0,166.0,229.0,63.0,203.800000,30.240000,166.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,8.0,57.0,49.0,22.677795,16.074864,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,106.949534,102.911141,12.0
2,Mo0.39Ru0.61,6.90,Mo0.39 Ru0.61,42.0,44.0,2.0,43.220000,0.951600,44.0,50.0,...,0.000000,0.000000,0.000000,0.0,194.0,229.0,35.0,207.650000,16.653000,194.0
3,Tm4Os6Sn19,1.10,Tm4 Os6 Sn19,50.0,76.0,26.0,58.000000,10.482759,50.0,37.0,...,0.000000,0.000000,0.000000,0.0,141.0,194.0,53.0,159.275862,23.947681,141.0
4,Nd1Bi0.99Pb0.01S2F0.3O0.7,4.85,Nd1 Bi0.99 Pb0.01 S2 F0.3 O0.7,8.0,83.0,75.0,36.658000,27.869600,16.0,19.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,72.206000,49.328776,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16409,Al4C3,0.00,Al4 C3,6.0,13.0,7.0,10.000000,3.428571,13.0,73.0,...,0.000000,0.000000,0.000000,0.0,194.0,225.0,31.0,211.714286,15.183673,225.0
16410,Nb0.96Ta0.04,8.87,Nb0.96 Ta0.04,41.0,73.0,32.0,42.280000,2.457600,41.0,47.0,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,8.0,82.0,74.0,27.138250,19.616202,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,117.531250,105.531250,12.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,8.0,70.0,62.0,24.705426,17.870921,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,110.488372,105.359654,12.0
16413,La5Si3,1.60,La5 Si3,14.0,57.0,43.0,40.875000,20.156250,57.0,13.0,...,0.000000,0.000000,0.000000,0.0,194.0,227.0,33.0,206.375000,15.468750,194.0

In [3]:
df_sc = df_sc[df_sc["Tc"]>=10]
df_sc

,composition,Tc,_Composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,Ba0.4K0.6Fe2As2,31.20,Ba0.4 K0.6 Fe2 As2,19.0,56.0,37.0,30.360000,6.214400,26.0,3.0,...,2.110663,0.844265,1.013118,0.0,166.0,229.0,63.0,203.800000,30.240000,166.0
1,Ca0.4Ba1.25La1.25Cu3O6.98,40.10,Ca0.4 Ba1.25 La1.25 Cu3 O6.98,8.0,57.0,49.0,22.677795,16.074864,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,106.949534,102.911141,12.0
6,La1.71Sr0.29Cu0.94Co0.06O4,33.00,La1.71 Sr0.29 Cu0.94 Co0.06 O4,8.0,57.0,49.0,24.195714,18.509388,8.0,8.0,...,1.548471,0.013273,0.026318,0.0,12.0,225.0,213.0,95.447143,95.368163,12.0
10,Nb3Sn0.85Tl0.15,18.20,Nb3 Sn0.85 Tl0.15,41.0,81.0,40.0,44.412500,5.118750,41.0,47.0,...,0.000000,0.000000,0.000000,0.0,141.0,229.0,88.0,208.987500,30.018750,229.0
11,Pb0.5Cu0.5Sr0.9La1.1Cu1O5.16,28.10,Pb0.5 Cu1.5 Sr0.9 La1.1 O5.16,8.0,82.0,74.0,24.310044,18.375508,8.0,8.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,101.290393,100.597910,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16400,Dy1Ba2Cu2.8Zn0.2O6.95,13.00,Dy1 Ba2 Cu2.8 Zn0.2 O6.95,8.0,66.0,58.0,24.772201,18.002594,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,108.432432,103.506626,12.0
16401,Bi2Ca2.5Sm0.5Cu2O8.33,22.00,Bi2 Ca2.5 Sm0.5 Cu2 O8.33,8.0,83.0,75.0,24.242661,19.035620,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,79.547293,91.032425,12.0
16408,La1.78Sr0.22Cu0.9975Zn0.0025O4,19.25,La1.78 Sr0.22 Cu0.9975 Zn0.0025 O4,8.0,57.0,49.0,24.403214,18.746531,8.0,8.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,95.391786,95.304898,12.0
16411,Pb2Sr2Ho0.5Ca0.5Cu2.982Al0.018O8,63.60,Pb2 Sr2 Ho0.5 Ca0.5 Cu2.982 Al0.018 O8,8.0,82.0,74.0,27.138250,19.616202,8.0,7.0,...,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,117.531250,105.531250,12.0
16412,Yb0.5Pr0.5Ba2Cu3O6.9,34.80,Yb0.5 Pr0.5 Ba2 Cu3 O6.9,8.0,70.0,62.0,24.705426,17.870921,8.0,9.0,...,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,110.488372,105.359654,12.0

In [4]:
X = df_sc.iloc[:, 3:]
y = df_sc['Tc']

In [5]:
df_sc['Tc']

0        31.20
1        40.10
6        33.00
10       18.20
11       28.10
         ...
16400    13.00
16401    22.00
16408    19.25
16411    63.60
16412    34.80
Name: Tc, Length: 6248, dtype: float64

In [6]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
X_train.shape

(4686, 132)

In [8]:
# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [9]:
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

Fitting 5 folds for each of 81 candidates, totalling 405 fits

In [10]:
# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Adjusted R-squared:", r2_score(y_test, y_pred, multioutput='uniform_average'))

Mean Squared Error (MSE): 114.00642806605562
R-squared: 0.8674465678003462
Mean Absolute Error (MAE): 6.63935088509373
Root Mean Squared Error (RMSE): 10.677379269561216
Adjusted R-squared: 0.8674465678003462

In [11]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,49.824858,0.549715,0.140626,0.000001,None,1,2,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-108.703283,-126.965161,-128.258291,-116.306622,-124.992614,-121.045194,7.448943,8
1,100.659089,0.472008,0.249999,0.039527,None,1,2,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-109.272867,-125.035972,-129.451332,-112.848794,-122.516441,-119.825081,7.577326,3
2,201.852554,2.850063,0.468749,0.045287,None,1,2,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-110.094774,-126.199986,-123.931248,-115.550643,-121.445518,-119.444434,5.871134,2
3,45.190498,0.585918,0.109378,0.039529,None,1,5,50,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-114.725106,-132.417324,-129.334749,-118.409615,-123.089510,-123.595261,6.581746,21
4,90.055995,0.840769,0.218750,0.051349,None,1,5,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",-111.628572,-128.663589,-125.551262,-116.000414,-123.131091,-120.994985,6.273843,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,25.740277,0.180678,0.063877,0.002755,20,4,5,100,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-117.364884,-138.091503,-136.869099,-124.779664,-128.509759,-129.122981,7.719197,41
77,54.417476,1.484792,0.110894,0.003036,20,4,5,200,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-116.770507,-135.994562,-136.807160,-120.876960,-131.300845,-128.350007,8.106804,33
78,12.703090,0.334826,0.034375,0.006251,20,4,10,50,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-120.933357,-140.129810,-140.469731,-124.531368,-135.157251,-132.244303,8.071568,52
79,27.196309,0.384763,0.056249,0.007653,20,4,10,100,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-118.159197,-139.472825,-140.176514,-124.628849,-131.443813,-130.776240,8.502019,47
80,52.159582,7.972809,0.090393,0.018386,20,4,10,200,"{'max_depth': 20, 'min_samples_leaf': 4, 'min_...",-120.232679,-139.527429,-140.016483,-124.500775,-133.477878,-131.551049,7.960035,49

In [12]:
# Assuming you have the 'best_model' already trained
filename = 'sc_ep_best_model_rf__2.pkl'
with open(filename, 'wb') as f:
    pickle.dump(best_model, f)

In [13]:
# Mean Squared Error (MSE): 128.98800337163584
# R-squared: 0.8252465683616537
# Mean Absolute Error (MAE): 5.709746142892196
# Root Mean Squared Error (RMSE): 11.357288557205713
# Adjusted R-squared: 0.8252465683616537

In [14]:
# # Example: Create a new data point (features) for prediction
# new_data_point = [[feature1_value, feature2_value, ...]]

# # Predict using the loaded model
# predicted_value = loaded_model.predict(new_data_point)

# print("Predicted value:", predicted_value)

In [15]:
# Mean Squared Error (MSE): 3.6857372748369126e-06
# R-squared: 0.9973982295162389
# Mean Absolute Error (MAE): 6.51226710603105e-05
# Root Mean Squared Error (RMSE): 0.0019198274075647823
# Adjusted R-squared: 0.9973982295162389

# Superconductivity
df_sc_ep = pd.read_csv("df_sc_ep_ElementProperty_Magpie_ftd.csv").dropna()

df_sc_ep = df_sc_ep.iloc[0:700]

X = df_sc_ep.iloc[:, 3:]
y = df_sc_ep['Tc']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Build the model
model = RandomForestRegressor()

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Evaluate the model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Print evaluation metrics
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

# Define a function to create the target column
def is_semiconductor(Tc):
    # A semiconductor has a band gap between 0.1 and 4 eV
    return 0.1 <= Tc <= 4